# Generated by Django 5.1.5 on 2025-05-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novation',
        ),
    ]
