# Generated by Django 5.1.5 on 2025-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_delete_novation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/default_avatar.png', null=True, upload_to='profile/'),
        ),
    ]
