# Generated by Django 5.2 on 2025-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_delete_novation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/profile_foto.png', null=True, upload_to='profile/'),
        ),
    ]
