# Generated by Django 5.2 on 2025-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='USE COMA'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
