# Generated by Django 5.2 on 2025-04-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='description',
        ),
    ]
